tools/python/om_display.py

Simply updating the header of the file to acknowledge the ERC funding

Update the funding origin of om_display.py

---

OpenMEEG/Wrapping/src/openmeeg.i

Correct the python regression.

Correct copy of array.

---

appveyor.yml

@agramfort @papadop Sorry for being late, I've corrected appVeyor.
Now we have the artifacts.

Correct AppVeyor.

---

.travis.yml
build_tools/travis/before_install.sh
build_tools/travis/install.sh

use libmatio with hdf5 support from brew on mac os x on travis

use of libmatio with hdf5 support from brew on mac os x

---

OpenMEEG/cmake/VtkOption.cmake
OpenMEEG/tools/add_dataset_to_vtk.cpp

VTK: remove unnecessary vtk libs import.

---

.travis.yml
OpenMEEG/libs/OpenMEEGMaths/tests/full.cpp
build_tools/travis/before_install.sh
build_tools/travis/install.sh

mainly for travis (don't worry I'll fix that soon)

temporarly removing the pseudo inverse test, as casuing troubles on Mac and Win.

---

OpenMEEG/libs/OpenMEEG/include/integrator.h

[MRG] cosmit: replace class into typename

---

CMakeLists.txt
OpenMEEG/cmake/UseOpenBLAS.cmake
cmake/externals/installOpenBLAS.cmake
cmake/externals/projects_modules/OpenMEEG.cmake

Improve OpenBLAS option for windows

---

.travis.yml
build_tools/travis/after_success.sh
build_tools/upload_package_gforge.py

from	
build\OpenMEEG-2.3.0.2-Win64-OpenBLAS-static.tar.gz
to
OpenMEEG-2.3.0.2-Win64-OpenBLAS-static.tar.gz

correct path for sftp from windows appveyor

---

cmake/Packaging.cmake
cmake/externals/ConfigureExternalProjects.cmake

is it ok like this Theo ? @papadop

minor: grouping subprojects into a list.

---

OpenMEEG/libs/OpenMEEG/include/Properties.H

Properties.H was lax in the way it was handling things. Tidied up. It is now the work of the caller to do the proper messages and exit.

Properly add exception in properties

---

.appveyor.yml
.travis.yml

Towards a release

---

.travis.yml
build_tools/travis/before_install.sh
build_tools/travis/script.sh

linux binaries are still broken as vtk libs are missing from package.
I am setting up travis to show the bug and I will remove vtk from distrib until it's fixed

Fix linux packaging

---

.mailmap

so :
git shortlog -n -s
gives:
707  Theodore Papadopoulo
559  Emmanuel Olivi
346  Alexandre Gramfort
74  Maureen Clerc
12  Perrine Landreau
5  Renaud Keriven
4  Yaroslav Halchenko
2  Daniel Miklody
2  Kyle Beauchamp
2  Dang Kai
2  Thierry Guillemot
1  Boris Burle
1  lazyparser
1  Marmaduke Woodman
1  Sylvain Vallaghe

add mailmap to summarize contribs for the release email

---

OpenMEEG/cmake/OpenMEEGOptions.cmake
build_tools/travis/script.sh

this is option 2 with global config...

fix rpath for tools on linux version 2

---

OpenMEEG/CMakeLists.txt
OpenMEEGMaths/CMakeLists.txt
apps/tools/CMakeLists.txt

[MRG] add soname to libs

---

README.rst

see #290 
cc: @agramfort @sagitter

[MRG] Add Fedora instructions in how to install binary OpenMEEG

---

.travis.yml

[hot-fix] Remov Cov info from shipping binaries

---

README.rst
openmeeg.rb

our current recommendation for brew installation was broken

change install instructions using homebrew on mac

---

.lgtm.yml
OpenMEEG/include/mesh.h
OpenMEEG/include/options.h
apps/cpuChrono.h
cmake/thirdParties.cmake

add lgtm yml file

---

CMakeLists.txt
cmake/Packaging.cmake
cmake/install.cmake

Fixing https://github.com/openmeeg/openmeeg/issues/314

fixing #314 using the same mechanism as https://github.com/CBICA/CaPTk/pull/490

---

.travis.yml

This PR:
- would fix travis (for second entry of our matrix)
- update linux virtual machines to use ubuntu-1804:bionic

MNT: update travis to bionic

---

.travis.yml
documentation/CMakeLists.txt
documentation/reference/CMakeLists.txt
wrapping/src/CMakeLists.txt
wrapping/src/openmeeg.i

A small changes to re-enable docstrings in the python module...

Docstrings

---

wrapping/src/test_doc.py
wrapping/src/test_geom_import.py
wrapping/src/test_make_geometry.py
wrapping/src/test_matrix.py
wrapping/src/test_mesh.py
wrapping/src/test_python2.py
wrapping/src/test_sensors.py
wrapping/src/test_vector.py

@papadop this is just a cosmestic PR to format the python more following the pep8 standard.

fix some pep8 errors

---

README.rst

Added warning regarding old age of OpenMEEG packages in NeuroDebian to README.rst.

Warn about old age NeuroDebian packages to README.rst

---

CMakeLists.txt
README.rst

Will merge, cut 2.4.2, then bump back to 2.4.9999 once CIs come back happy

MAINT: Bump version

---

.github/workflows/build_and_test.yml
build_tools/cmake_configure.sh
build_tools/setup_windows_compilation.sh
cmake/options.cmake
wrapping/python/CMakeLists.txt

Hopefully has no effect here but might help https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=533702&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c&t=3cc4a9ed-60e1-5810-6eb3-5f9cd4a26dba

FIX: Try another way to copy

---

.github/workflows/build_and_test.yml
.gitignore
codecov.yml

MAINT: Reenable codecov

---

.github/workflows/build_and_test.yml
cmake/CompilerOptions.cmake
cmake/options.cmake
wrapping/python/openmeeg/tests/test_mesh.py

Let's see if we can replicate https://github.com/openmeeg/openmeeg/issues/460

MAINT: Add latest OpenBLAS and PyPy

---

OpenMEEG/include/forward.h

BUG: Protect zero case

---

OpenMEEG/include/forward.h

Just completely avoid to set up the random noise generator if it is not to be used.

Slightly improve the previous fix.

---

OpenMEEG/include/GeometryIO.h
data/Head1/Head1_legacy.geom
tests/CMakeLists.txt

Add a test and improve slightly the message given when an unknown file format is provided (identified by the file extension).

Add legacy file format test

---

OpenMEEGMaths/include/Exceptions.H
OpenMEEGMaths/include/range.h
OpenMEEGMaths/include/ranges.h

Un-revert the Block API (commit 1). This one should not be problematic as it just adds new classes.

Add missing exception for block API.

---

OpenMEEGMaths/include/Exceptions.H
OpenMEEGMaths/include/range.h
OpenMEEGMaths/include/ranges.h

Block api exceptions

---

.github/workflows/build_and_test.yml
.github/workflows/cibuildwheel.yml

DOC: Document CIs

---

OpenMEEG/include/mesh.h

This starts to introduce some range methods into the mesh class. They are not yet used, so it should not perturb build and testing.

Introduce range methods.

---

OpenMEEG/include/GeometryExceptions.H
OpenMEEG/include/analytics.h
OpenMEEG/include/assemble.h
OpenMEEG/include/danielsson.h
OpenMEEG/include/gain.h
OpenMEEG/include/integrator.h
OpenMEEG/include/operators.h
OpenMEEG/include/sensors.h
OpenMEEG/src/assembleHeadMat.cpp
OpenMEEG/src/assembleSensors.cpp
OpenMEEG/src/assembleSourceMat.cpp
OpenMEEG/src/danielsson.cpp
OpenMEEG/src/operators.cpp
OpenMEEG/src/sensors.cpp
OpenMEEGMaths/include/symm_block_matrix.h
apps/assemble.cpp
apps/tools/project_sensors.cpp
tests/test_validationEIT.cpp
wrapping/python/openmeeg/tests/test_doc.py

This adds the block API to OpenMEEG. This also reorganizes some pieces of code notably by replacing trivial classes with functions and the ways operators are defined.

OpenMEEG block api

---

OpenMEEG/include/operators.h

Just a small update of a comment and an inlining of a private method used only once/

Minor reorganization of the code and comment update.

---

.github/workflows/build_and_test.yml
cmake/utils/CheckCXXFeatures.cmake
cmake/utils/cxx_tests/openmp_support.cpp

Try to see if we can test OpenMP on MacOS.

Add missing library for MacOS OpenMP support.

---

.github/workflows/build_and_test.yml
build_tools/cmake_configure.sh
cmake/thirdParties.cmake

Should reenable VTK on Ubuntu builds. If this slows them down much then I'll restrict which CIs it runs on more.

MAINT: Test VTK

---

build_tools/cibw_test_command.sh
wrapping/python/openmeeg/tests/test_sensors.py
wrapping/python/openmeeg/tests/test_vector.py

I don't expect this to work, but locally on my M1 machine at least things passed, so I'm curious to see which CIs fail.

MAINT: Restore skipped tests

---

OpenMEEG/include/assemble.h
OpenMEEG/src/assembleSourceMat.cpp

Add a function to fix compute_leadfields.py of git:openmeeg_sample_data.

---

.github/workflows/build_and_test.yml
cmake/CompilerOptions.cmake

MAINT: Remove mingw64

---

OpenMEEGMaths/include/sparse_matrix.h
OpenMEEGMaths/src/sparse_matrix.cpp

While cleaning up the windows pragma, I noticed that the sparse matrix code need a small cleanup to use more modern C++.
This is what this PR does.

Move to more modern C++ syntax.

---

.github/workflows/build_and_test.yml
OpenMEEG/include/GeometryIOs/GeomFile.h
OpenMEEG/include/commandline.h
OpenMEEG/include/filenames.h
apps/tools/vtp_to_meshes.cpp
build_tools/cibw_before_all.sh
build_tools/cmake_configure.sh
wrapping/python/setup.py

Let's see if this works
Closes #542

MAINT: Use std::filesystem

---

.github/workflows/build_and_test.yml
.github/workflows/cibuildwheel_apps.yml

The action on `main` failed:
https://github.com/openmeeg/openmeeg/runs/8050353767?check_suite_focus=true
Let's try again

MAINT: Iterate on release

---

OpenMEEG/include/GeometryIOs/GeomFile.h
wrapping/python/openmeeg/tests/conftest.py
wrapping/python/openmeeg/tests/test_python.py

I expect this to be okay on Linux and macOS but fail on Windows, indicating an issue with file pointer release there

BUG: Fix unclosed file pointer on Windows

---

README.rst

@papadop this is how I've debugged on each OS

DOC: Document local builds [ci skip]

---

build_tools/setup_vcpkg_compilation.sh

Let's see if this leads to green CIs, then we can do all the dependabot stuff.

MAINT: Update vcpkg

---

.github/workflows/build_and_test.yml
CMakeLists.txt
OpenMEEGMaths/include/MatlabIO.H

BUG: Fix bug with matio log call

---

wrapping/python/pyproject.toml

Should fix https://github.com/openmeeg/openmeeg/actions/runs/9195015420/job/25290371709

MAINT: Restore TestPyPI uploads

---

.github/workflows/build_and_test.yml
.github/workflows/cibuildwheel.yml
.github/workflows/cibuildwheel_apps.yml
README.rst
build_tools/cibw_before_all.sh
build_tools/cibw_before_all_apps.sh
build_tools/setup_vcpkg_compilation.sh
tests/test_validationEIT.cpp
wrapping/python/pyproject.toml

Closes #663
Hopefully it's easy! 🤞

ENH: Add aarch64 linux wheel build

---

.github/workflows/cibuildwheel.yml
.github/workflows/cibuildwheel_apps.yml

MAINT: Use native Linux arm64 runners
