openmeeg/openmeeg

Wrapping/src/numpy.i, Wrapping/src/openmeeg.i, cmake/CompileOptions.cmake, libs/OpenMEEGMaths/include/MathsIO.H, libs/OpenMEEGMaths/include/MatlabIO.H, libs/OpenMEEGMaths/include/TrivialBinIO.H
2 commits in a same pull request.
The first make us require a C++-11 compiler. This homogeneize the code between unix/Mac and Visual C++ (which is by default since VS 12). C++-11 support is available (but with a flag) in clang and g++ since version 4.8. Note that we use nothing particular to C++-11, but there are some library incompatibilities in the conversions of file streams and results of read on streams to bool (now the cast has to be made explicitely).
The second change removes some warnings coming from openmeeg python support. I activated the numpy strict API which is available since numpy 1.7 (currently at 1.10) and modified the code appropriately (mainly use some macros to access fields of the numpy structure + some small name changes).
=> C++11 and numpy 1.7 API

libs/OpenMEEG/src/sensors.cpp
The nearest triangle is put into the list twice when searching triangles for sensors with a radius, which makes the total electrode area incorrect.
=> Bug fix for sensors with a radius

OpenMEEG/libs/OpenMEEGMaths/include/Exceptions.H, OpenMEEG/libs/OpenMEEGMaths/include/MatlabIO.H
The title says it all. Compatible with stock matio.
Unfortunately not very easy to test. I ended up using om_matrix_info with a matlab (mat5) file in which I modified the header. Other test (with mat73 files) seem to show that Hdf5 errors are not (at least all) catched. But this is at leat an incremental improvement.
closes #65
=> Add a way to catch at least some matio errors.

.travis.yml, OpenMEEG/libs/OpenMEEGMaths/include/BlasLapackImplementations/OpenMEEGMathsvecLibConfig.h
choosing BLASLAPACK_IMPLEMENTATION=Auto 
uses in priority OpenBLAS (on MAC as in linux).
so the vecLib, was not tested.
=> [MRG] fix support for vecLib on Mac + restore this case on travis.

OpenMEEG/libs/OpenMEEG/src/assembleHeadMat.cpp, OpenMEEG/libs/OpenMEEGMaths/include/matrix.h, OpenMEEG/libs/OpenMEEGMaths/src/matrix.cpp, OpenMEEG/libs/OpenMEEGMaths/tests/full.cpp
- correct failing test due to non-initialized memory
- use a sparseMatrix to store the diagonal S in the svd.
- return the transposed V in the svd
=> [MRG] fixing the pseudo inverse test.

OpenMEEG/cmake/OpenMEEGOptions.cmake
this avoids the need to set DYLD_LIBRARY_PATH on my mac after doing a make install in a custom folder.
maybe this can be helpful for our problem on mac @eolivi
=> tell cmake to use rpath to avoid having to set DYLD_LIBRARY_PATH

OpenMEEG/CMakeLists.txt
the tools were still showing they were compiled with 2.3.99
please accept this PR as soon as you think we're really good for release 2.4
=> Update OpenMEEG version to 2.4

OpenMEEG/src/geometry.cpp, OpenMEEG/src/interface.cpp, OpenMEEG/src/sensors.cpp, cmake/CompilerOptions.cmake
[written by Sik]
This PR responds to The problem of using coarse compiler options as a wildcard when doing multiplatform software. Cutting corners to use alternative operators by changing the compiler options (with all its collateral effects) instead of adding the bearly minimum, means that all have been chasing ghosts for 2.5 weeks. It was much easier to just add the alternative macros to those 3 cpp files that need it.
Fix #312. Close #313.
=> [BUG-fix] don't use fancy c++ with /Za option in MSVC

OpenMEEGMaths/include/MatlabIO.H
Let's see what breaks with Matlab 73 format...
=> [WIP] attempt to use mat73 for IO

.appveyor.yml
Explicit is better than implicit. 
This PR should had prevented `Missing "-C <config>"` here https://ci.appveyor.com/project/openmeegci/openmeeg/builds/25289498#L7087
=> MAINT: use explicit configuration

.appveyor.yml, .travis.yml
On internet two solution are proposed:
- downgrade to conda 4.3.34
- avoid path manipulation and instead call a script (see https://github.com/conda/conda/issues/8836)
Attempting the last one.
=> Attempt to fix conda failure in appveyor

OpenMEEGMaths/include/MatlabIO.H
closes #421
This is an adaptation to a new interface that appeared with matio-1.5.18.
It is just a small type change.
Note that the testers will only (for now) check that the code compiles with versions older than 1.5.18 (as this is what is inslled on the testers), but I checked on my side that the change (which is quite obvious) works with 1.5.18.
=> Adapt MatlabIO.H to handle both older and newer version of matio 

OpenMEEGMaths/src/vector.cpp
Replaced `<<` with `>>` in the `Vector::load` function.
=> Modified a typo in the `Vector::load` function

.github/workflows/build_and_test.yml, .github/workflows/cibuildwheel.yml
1. Switch jobs to msvc by default
2. Simplify job naming by using an explicit `include` list rather than matrix entries + include
3. Use `${{steps.env-vars.outputs.*}}` instead of `${{matrix.*}}` so that defaults can be populated by the `env-vars` step
This should reduce our build time and number of jobs a tiny bit
=> MAINT: Use MSVC by default

OpenMEEG/include/MeshIOs/mesh.h, OpenMEEGMaths/include/OMassert.H, tests/test_mesh_ios.cpp
When doing something else, I made some index error and saw that assert never throws the intended exception 
(so that we get tons of messages).
This was hiding a bug in the mesh file format (from BrainVisa I guess) reader, which I attempted to correct, but I do not find the documentation for that file format (broken link in an old BrainVisa forum). So I had to improvise. I ended supposing that the reader was correct and the writer not. Checked that I could read an old brainvisa .mesh file I had on a disk. I guess that if the reader was wrong, there is zero chance that om_mesh_info would say "Mesh orientation correct (valid for closed mesh)."
If you know a reader (in mne python ?) or a documentation for that format , I'd be happy to check I made the right choice.
That also probably means …
=> Assert rework

wrapping/python/openmeeg/openmeeg.i
Calling PyErr_SetString does not interrupt the program flow, so does not generate the expected exception. The program was continuing so eventually not even generating an error or not the first one. This happened when an "extend" was calling other "extend" functions/methods. Instead, I introduced exceptions and let the swig mechanism to handle exceptions to deal with those.
The messages are also improved, so instead of and uninformative runtime error (because for some reason the PyErr_SetString message was lost), we now get:
>>> mesh1 = om.Mesh(np.array([[0.0, 0.0, 0.0]]), triangles)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/papadop/compiles/OpenMEEG/OpenMEEG-ref-f36/wrapping/python/openmeeg/openmeeg.py", line 1306, in __init__ …
=> Improved Python error handling

.github/workflows/build_and_test.yml, build_tools/cibw_test_command.sh, wrapping/python/openmeeg/tests/test_mesh.py
Toward https://github.com/openmeeg/openmeeg/issues/508, let's see what fails if we remove all BAD_PYPY skips.
=> MAINT: Remove PyPy test skips

OpenMEEG/include/DataTag.H, OpenMEEG/include/commandline.h, OpenMEEGMaths/include/MathsIO.H, OpenMEEGMaths/include/OpenMEEGMathsConfig.h
I noticed that some of the windows pragmas are related to old stuff that was removed years ago (exception specifications, ...). Trying to remove some of those (Removing even more WIN32 material)....
=> Remove no longer useful pragmas.

.github/workflows/build_and_test.yml, wrapping/python/openmeeg/tests/test_doc.py, wrapping/python/openmeeg/tests/test_make_geometry.py, wrapping/python/openmeeg/tests/test_mesh.py, wrapping/python/openmeeg/tests/test_python.py, wrapping/python/openmeeg/tests/test_python2.py, wrapping/python/openmeeg/tests/test_sensors.py, wrapping/python/openmeeg/tests/test_vector.py
Toward #508, let's see what fails if we remove all ~~`BAD_MSVC`~~ `BAD_MKL` skips.
Closes #508
=> MAINT: Restore test on MKL

wrapping/python/openmeeg/_distributor_init.py, wrapping/python/openmeeg/_make_geometry.py, wrapping/python/openmeeg/_version.py, wrapping/python/openmeeg/tests/conftest.py, wrapping/python/openmeeg/tests/test_doc.py, wrapping/python/openmeeg/tests/test_geom.py, wrapping/python/openmeeg/tests/test_make_geometry.py, wrapping/python/openmeeg/tests/test_matrix.py, wrapping/python/openmeeg/tests/test_mesh.py, wrapping/python/openmeeg/tests/test_python.py, wrapping/python/openmeeg/tests/test_sensors.py, wrapping/python/openmeeg/tests/test_vector.py, wrapping/python/setup.py
Over in https://github.com/openmeeg/openmeeg/pull/553 I hit an error because we had no `flake8`-sort of checking going on (`pyflakes` would have caught it), so I want to add some Python style checks to CIs.
At the same time, many scientific Python groups are moving to `black` (NumPy, scikit-learn). It seems like a good time since there isn't too much Python code in the repo, and we can just standardize around it easily.
In this PR I'm:
1. changing the Python code to conform to these styles
2. adding a pre-commit hook that enables automatic `black` formatting if people want to `pre-commit install` it, but it's not required
3. adding CI checks for `black` and `flake8` compliance
This should go in after https://github.com/openmeeg/openmeeg/pull/553, hence the WIP
=> MAINT: Correct code for black and flake8

.git-blame-ignore-revs, .github/workflows/style.yml, .pre-commit-config.yaml, wrapping/python/MANIFEST.in, wrapping/python/setup.cfg
Second part of transitioning to black+flake8:
1. Add to CI
2. Add optional pre-commit hook support
3. Ignore the style commit in blame
Will mark for auto-merge and then add lint to the required CIs in branch protection rules
=> CI: Use black and flake8

cmake/options.cmake
Minor change (invisble to the user/developper) for a more canonical cmake code for CTest (following issue #316).
=> More canonical cmake testing.

OpenMEEG/include/assemble.h, OpenMEEG/include/gain.h, apps/assemble.cpp, wrapping/python/openmeeg/tests/test_python.py
@agramfort was just hit by a bug where `DipSourceMat` was not working properly because he didn't specify that `domain_name='brain'`. This PR makes the `domain_name` a mandatory argument, which seems safer than ~~allowing it to be~~ defaulting it to an empty string.
=> BUG: Force users to specify domain_name

build_tools/cibw_before_all.sh, wrapping/python/openmeeg/_version.py
I'm going to tell the wheels not to use OpenMP, then merge. This will cause a testpypi upload, which we can then use in https://github.com/mne-tools/mne-python/pull/11011 where we have observed failures. If this comes back green for the run that uses the `testpypi` wheel (maybe after a restart or two?), we can conclude that something is wrong with our use of OpenMP on Windows that's causing the failures. We already had to disable it on macOS for @agramfort locally, so it wouldn't surprise me at all if this is the case.
=> MAINT: Disable OpenMP on Windows for now

OpenMEEG/include/assemble.h, OpenMEEG/include/integrator.h, OpenMEEG/include/operators.h, OpenMEEG/src/assembleHeadMat.cpp, OpenMEEG/src/assembleSourceMat.cpp, wrapping/python/openmeeg/openmeeg.i, wrapping/python/openmeeg/tests/test_doc.py, wrapping/python/openmeeg/tests/test_python.py
When running in Python, these outputs so far are mandatory:
https://github.com/mne-tools/mne-python/runs/8145144458?check_suite_focus=true#step:13:602
```
mne/forward/tests/test_make_forward.py::test_make_forward_solution_ctf[testing_data-MNE-C] PASSED [ 15%]
mne/forward/tests/test_make_forward.py::test_make_forward_solution_ctf[testing_data-openmeeg] OPERATOR S ... (arg : mesh Cortex , mesh Cortex )
OPERATOR N ... (arg : mesh Cortex , mesh Cortex )
OPERATOR D ... (arg : mesh Cortex , mesh Cortex )
OPERATOR S ... (arg : mesh Skull , mesh Cortex )
OPERATOR N ... (arg : mesh Skull , mesh Cortex )
OPERATOR D ... (arg : mesh Skull , mesh Cortex )
OPERATOR D*... (arg : mesh Skull , mesh Cortex )
OPERATOR S ... (arg : mesh Skull , mesh Skull )
OPERATOR N ... (arg : mesh Skull , mesh Skull ) …
```
=> ENH: Add verbose argument to HeadMat, expose Integrator

.github/workflows/codeql-analysis.yml, OpenMEEG/include/NullStream.h, OpenMEEG/include/assemble.h, OpenMEEG/include/logger.h, OpenMEEG/include/om_common.h, OpenMEEG/include/operators.h, OpenMEEG/include/progressbar.h, OpenMEEG/src/assembleHeadMat.cpp, OpenMEEG/src/assembleSourceMat.cpp, cmake/Findmatio.cmake, wrapping/python/openmeeg/__init__.py, wrapping/python/openmeeg/openmeeg.i, wrapping/python/openmeeg/tests/test_doc.py, wrapping/python/openmeeg/tests/test_python.py
This adds a new logging system that is better (in my view) than passing a verbose bool on all relevant function. Basically, we have a log_stream(XX) function that provides a logging stream which is decided on the value of XXX to be either std::cout or a null stream. Several logging levels are defined but only two are exploited at this time (INFORMATION and PROGRESS).
The class Logger keeps (with a static member the global state of the logger. For now, I have disabled the logging globally for python (see __init__.py), but it may be meaningful to disable it only for mne....
Compared to the previous solution, it also includes the progressbars.
So far, I kept this only for OpenMEEG (i.e not OpenMEEGMaths).
=> New logging system

.github/workflows/build_and_test.yml, build_tools/cibw_before_build_windows.sh, wrapping/python/.gitignore, wrapping/python/CMakeLists.txt, wrapping/python/openmeeg/__init__.py, wrapping/python/openmeeg/_make_geometry.py, wrapping/python/openmeeg/_utils.py, wrapping/python/openmeeg/tests/test_geometry.py, wrapping/python/openmeeg/tests/test_mesh.py, wrapping/python/openmeeg/tests/test_python.py, wrapping/python/openmeeg/tests/test_vector.py, wrapping/python/setup.cfg, wrapping/python/setup.py
@papadop feel free to merge if you're happy
Then you can rebase #594 or merge `main` into it. But it might actually be easier to start from a new branch to make the related `CMakeFiles.txt` fixes after this is merged.
=> MAINT: Rename internal _openmeeg_cxx -> _openmeeg_wrapper

.github/dependabot.yml
We should use `dependabot` to avoid things like checkout and setup-python from getting out of date. Will probably need to add a skip for the `cibuildwheel` one that causes an `ELF` error until I can figure that one out.
=> MAINT: Use dependabot

.github/workflows/build_and_test.yml, .github/workflows/cibuildwheel_apps.yml, build_tools/cibw_before_all_apps.sh, build_tools/cibw_before_build.sh, build_tools/cibw_before_build_windows.sh, wrapping/python/openmeeg/_version.py, wrapping/python/pyproject.toml
NumPy 2.0 RC is imminent. Let's make sure we have infrastructure to build all against 2.0 and bump the `.dev` version number so a new release shows up on TestPyPI.
=> MAINT: Ensure compat with NumPy 2.0 on PyPI

.github/workflows/build_and_test.yml, .gitignore, CMakeLists.txt, build_tools/cibw_before_all.sh, build_tools/cibw_before_all_apps.sh, build_tools/cibw_before_build_windows.sh, wrapping/python/CMakeLists.txt
Unexpected behavior with git archival and setuptools_scm:
```
larsoner:~/Desktop/openmeeg-2.5.9/wrapping/python$ python -m setuptools_scm -c pyproject.toml
('ERROR: no version found for', Namespace(root=None, config='pyproject.toml', strip_dev=False, command=None))
```
so instead let's do
```
larsoner:~/Desktop/openmeeg-2.5.9$ python -m setuptools_scm -c wrapping/python/pyproject.toml
2.5.9
```
=> FIX: Hotfix for git archival

.github/workflows/cibuildwheel.yml, build_tools/cibw_before_build_windows.sh, wrapping/python/pyproject.toml
NumPy doesn't provide pp39 aarch64 wheels, let's avoid it. And let's add a `before-build` that makes sure we only build on platforms that have an associated NumPy binary wheel.
=> MAINT: Speed up emulated wheel build

.github/workflows/build_and_test.yml, .github/workflows/cibuildwheel.yml, .github/workflows/cibuildwheel_apps.yml
`continue-on-error: true` can lead to "successful" builds that had a failing step when `if: always()` is used, so just avoid it. Achieve the desired effect of not killing other *jobs* early with `fail-fast: false` instead.
=> MAINT: Dont use continue-on-error

CMakeLists.txt, build_tools/cibw_before_build_windows.sh, build_tools/cibw_test_command.sh, build_tools/cmake_configure.sh, wrapping/python/openmeeg/__init__.py, wrapping/python/pyproject.toml, wrapping/python/setup.py
:crossed_fingers: that this works, in which case I'll quickly cut a 2.5.14. Fortunately there probably aren't many end-users using warnings-as-errors, but it's a problem for MNE-Python for example (which does so in its test suite).
=> BUG: Work around SWIG segfault on import with warnings-as-error
